### PR TITLE
remake-ifying NHD processing

### PR DESCRIPTION
**Pull request by lawinslow**
@mhines-usgs want to take a look?

### CODE REVIEW

**Comment by lawinslow** [comment]
https://github.com/USGS-R/necsc-lake-modeling/pull/51/files?w=1

**Comment by mhines-usgs** [comment]
This looks cool to me, do you want me to try and run it and make sure it goes or have you already done that?

**Comment by lawinslow** [comment]
If you're ok, let's just merge, I want to keep moving forward and a merge will help me separate this and my additions for max depth.

**Comment by jordansread** [comment]
I thought we weren't checking in shapefiles to the repo? `data/statedata/cb_2014_us_state_5m.shp`?

**Comment by lawinslow** [comment]
Up to you guys. It's supporting information and its small. What's the policy on checking data into the repo?

**Comment by jordansread** [comment]
Fine by me if it is all states

**Pull request merged**
