### PR TITLE
adding michigan data joined with nhd permid

### PR DESCRIPTION
**Pull request by mhines-usgs**
@jread-usgs wasn't sure where to put this but this is the michigan data joined with permids from the NHD medium dataset. There are quite a few non-matches at the bottom of the csv...

### CODE REVIEW

**Comment by jordansread** [comment]
what was the criteria for a match here? Did you look at any of the non-matches to see if they were funky flowage lakes that the centroid may have fallen outside of the waterbody?

**Comment by lawinslow** [comment]
@mhines-usgs you may want to re-check the linking. While some of the non-linked lakes are due to centroid issues or might be smaller than 4 ha (and there are a few zeros in lat/lon), a lot should be fine

Like this one. 
image

**Comment by mhines-usgs** [comment]
Not sure, I can re-try the join but I just took the NHD Medium dataset and did a spatial join in arcMap. If that feature isn't in the NHD medium dataset (?) it would fail to match. Will double-check...

**Comment by mhines-usgs** [comment]
For whatever reason, the spatial join is going to need a slight buffer. I'll try again shortly. Green are missing slightly, pink are matching fine.

image

**Pull request merged**
